# Generated by Django 3.2.5 on 2021-08-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodordermodel',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
