# Generated by Django 3.2.5 on 2021-08-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_alter_foodordermodel_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodordermodel',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
    ]
